#!/bin/bash

wget -qO- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
nvm install --lts

npm i diff-so-fancy -g
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
