#!/bin/bash
sudo apt-get -y install git git-core

git config --global user.email "billmwong@gmail.com"
git config --global user.name "Bill Wong"

git config --global core.editor "vi"
git config --global push.default "current"

ssh-keygen -t rsa -b 4096 -C "billmwong@gmail.com"
