#!/bin/bash
# would recommend copy-pasting each line instead of running whole script

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo apt-get -y install zsh
    wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh 
    cd $HOME
    rm -f .zshrc
    wget https://github.com/billmwong/dotfiles/raw/master/.zshrc
    sudo git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
    chsh -s `which zsh`
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # for mac
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | zsh 
    cd $HOME
    git clone https://github.com/billmwong/dotfiles.git
    # add line to .zshrc:
    # source $HOME/dotfiles/.zshrc

    chsh -s /bin/zsh

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew install fzf
fi

# Computer restart may be required
