#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo apt-get -y install zsh
    wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh 
    cd $HOME
    rm -f .zshrc
    wget https://github.com/billmwong/dotfiles/raw/master/.zshrc
    sudo git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
    chsh -s `which zsh`
elif [[ "$OSTYPE" == "darwin"* ]]; then
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | zsh 
    cd $HOME
    rm -f .zshrc
    curl -O https://raw.githubusercontent.com/billmwong/dotfiles/master/.zshrc
    # sudo git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

    chsh -s /bin/zsh

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew install fzf
fi

# Computer restart may be required
